### ISSUE TITLE
face_recognition no run

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [mesakarghm/CV#1]
C:\Users\usuario\Documents\Dev\Python\CV\face-recognition-opencv>python recognize_faces_video.py --encodings encodings.pickle
Traceback (most recent call last):
  File "recognize_faces_video.py", line 7, in <module>
    import face_recognition
ModuleNotFoundError: No module named 'face_recognition'

C:\Users\usuario\Documents\Dev\Python\CV\face-recognition-opencv>

**Comment by mesakarghm** [comment]
@GCPBigData  Have you tried 
pip install face_recognition 

It's possible you haven't installed the face_recognition library. Also, face_recognition and dlib requires Cmake to be installed in your system. Please check for the installation of Cmake as well.
